### ISSUE TITLE
No module named PyVista

### ISSUE THREAD

**Issue by bhargav1195** [napoles-uach/Pyvista_streamlit#1]
Thank you so much for the demo example, I tried it and it worked on localhost.

However, when I try to upload it on cloud, I am getting error 

********************************
Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/scriptrunner/script_runner.py", line 475, in _run_script
    exec(code, module.__dict__)
  File "/app/streamlit/m1.py", line 4, in <module>
    import pyvista
ModuleNotFoundError: No module named 'pyvista'

********************************

Can you please suggest what I am doing wrong?

**Comment by napoles-uach** [comment]
Hi @bhargav1195, thanks for your message!
Are you using the requirements.txt and packages.txt files in your repo? If not, please do it, or simply fork my repo. Whit that, I think it should work.
Let me know if this solves your problem 👍

**Comment by bhargav1195** [comment]
HI @napoles-uach , 

Thank you so much for your response. It worked perfectly. Amazing.

**Comment by indahyani** [comment]
i get some error , could you help me

File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/scriptrunner/script_runner.py", line 557, in _run_script
    exec(code, module.__dict__)
File "Klasifikasi_Sawit1.py", line 4, in <module>
    import cv2
